--
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms.
-- By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four
-- million, find the sum of the even-valued terms.
--
--
-- THIS CODE IS A WORK IN PROGRESS --
--
-- Define the Fibonacci sequence:

fib 0 = 0; fib 1 = 1; fib n = fib(n-1) + fib(n-2)

-- Use filer, map and list comprehensions to generate the sequence we want:

euler002 = sum ( filter even (map fib [ x | x <- [1..100], (fib x) < 4000000 ] ) )

-- 4613732